[cursor]
blink_interval = 500

[cursor.style]
blinking = "On"

[font]
size = 15.0

[font.bold]
family = "SourceHanCodeJP"

[font.bold_italic]
family = "SourceHanCodeJP"

[font.italic]
family = "SourceHanCodeJP"
style = "Bold Italic"

[font.normal]
family = "SourceHanCodeJP"
style = "Bold"

[scrolling]
history = 50000

[window]
dynamic_title = true
opacity = 0.7

[window.dimensions]
columns = 80
lines = 20
