alias ls='ls -GF'
alias vim='/Applications/MacVim.app/Contents/bin/vim -u ~/.vim/vimrc -N'
alias gvim='/Applications/MacVim.app/Contents/bin/mvim -u ~/.vim/vimrc -U ~/.vim/gvimrc -N'
alias mvim='/Applications/MacVim.app/Contents/bin/mvim -u ~/.vim/vimrc -U ~/.vim/gvimrc -N'
alias vi='/Applications/MacVim.app/Contents/bin/vim -u ~/.vim/vimrc -N'

# if (which zprof > /dev/null) ;then
#   zprof | cat
# fi

# vim: ft=zsh
