# zmodload zsh/zprof && zprof

export PATH=/usr/local/bin:$HOME/.rbenv/shims:$HOME/.cabal/bin:$HOME/local/bin:$PATH


# fpath
fpath=(/usr/local/share/zsh-completions $fpath)

# rbenv
if which rbenv > /dev/null; then 
    eval "$(rbenv init - --no-rehash)";
fi

# OPAM
. $HOME/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# golang
export GOPATH=$HOME/.go
export PATH=$PATH:$GOPATH/bin

# cargo(rust)
export PATH=$PATH:$HOME/.cargo/bin

# vim: ft=zsh
