alias ls='ls -GF'
alias vim='/Applications/MacVim.app/Contents/MacOS/Vim "$@" -u ~/.vim/vimrc -N'
alias gvim='/usr/local/bin/mvim -u ~/.vim/vimrc -U ~/.vim/gvimrc -N'
alias mvim='/usr/local/bin/mvim -u ~/.vim/vimrc -U ~/.vim/gvimrc -N'
alias emacs='/usr/local/bin/emacs'
alias vi='/Applications/MacVim.app/Contents/MacOS/Vim "$@" -u ~/.vim/vimrc -N'

# if (which zprof > /dev/null) ;then
#   zprof | cat
# fi

# vim: ft=zsh
